<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DGB-C02VH08BH" failures="1" tests="10" name="ChordX API Automation" time="5.713" errors="0" timestamp="2019-09-13T11:50:35 PDT">
  <testcase classname="APITests.EquipmentTest" name="equipTest" time="1.128"/>
  <testcase classname="APITests.GetServerVersionTest" name="versionTest" time="0.064"/>
  <testcase classname="APITests.LiveDataTest" name="liveDataTest" time="0.54"/>
  <testcase classname="APITests.MaintenanceHistoryTest" name="maintenanceHistoryTest" time="0.898"/>
  <testcase classname="APITests.MaintenanceIssuesTest" name="maintenanceIssuesTest" time="0.139"/>
  <testcase classname="APITests.MaintenanceJobTest" name="maintenanceJobTest" time="0.47"/>
  <testcase classname="APITests.PerformanceDataTest" name="perfDataTest" time="0.584"/>
  <testcase classname="APITests.PlannedMaintenanceTest" name="plannedMaintenanceTest" time="0.977"/>
  <testcase classname="APITests.SensorsTest" name="sensorsTest" time="0.48">
    <failure type="java.lang.AssertionError" message="Test failed because of anomaly/anomalies. Please check the logs.">
      <![CDATA[java.lang.AssertionError: Test failed because of anomaly/anomalies. Please check the logs.
at org.testng.Assert.fail(Assert.java:97)
at APITests.SensorsTest.sensorsTest(SensorsTest.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
    </failure>
  </testcase> <!-- sensorsTest -->
  <testcase classname="APITests.SimulatorConfigTest" name="configTest" time="0.053"/>
</testsuite> <!-- ChordX API Automation -->
